### ISSUE TITLE
类似于  xxx.xxx.xxx.xx 这种的队列名称  文件名需要怎么写

### ISSUE THREAD

**Issue by timelessonly** [workbunny/webman-rabbitmq#13]

**Comment by timelessonly** [comment]
还有一个问题   文件名是否就是队列名
比如我有一个test队列  那文件名就必须为test

**Comment by chaz6chez** [comment]
这个插件无需去rabbitmq后台创建queue、exchange等操作，创建好builder后，启动消费者/生产者发布消息的时候会自动创建关联的内容；
如果是已经创建的队列想要接入builder，只需要将builder类中对应的queueName和exchangeName对应改成你在rabbitmq后台所创建的即可。

**Comment by timelessonly** [comment]
能给个示例吗？

**Comment by chaz6chez** [comment]
> 能给个示例吗？

非常不好意思，最近太忙了，1.x版本您可以参照以下方案实现
1. 创建一个CustomBuilder，实现BuilderInterface
2. 将FastBuilder的内容拷贝至CustomBuilder
3. 修改构造函数的内容，将queue命名的部分进行调整和修改

**Comment by timelessonly** [comment]
十分感谢
