### ISSUE TITLE
请教如何实现topic模式,exchange对应多个队列对应各自消费者

### ISSUE THREAD

**Issue by leedom-hub** [workbunny/webman-rabbitmq#15]
**感谢作者提供简单好用的插件!**

> 当前使用1.0版本

_我想实现的效果是:_
- 实现topic模式, 比如`exchange = mqTopic` , 
- 这个交换机有两个队列`mqTopic_1`和`mqTopic_2`,
- 两个队列分别通过`routing_key = task.1 (mqTopic_1)`和`routing_key = task.2 (mqTopic_2)`绑定
- 每个队列有各自的消费者进程去消费

_我的做法:_
- 通过`php webman workbunny:rabbitmq-builder mqTopic 2`创建了`builder`
- 投递消息使用`sync_publish()` **目前情况是投递消息可以到达,但是无法消费**
```php
$b = MqTopicBuilder::instance();
$b->setMessage(new Message([
         'exchange_name'     => 'mqTopic',
          'exchange_type'     => Constants::TOPIC,
          'queue_name'        => 'mqTopic_'.$request->get('queue_name', 0), //对应mqTopic_1 mqTopic_2
          'routing_key'       => $request->get('routing_key',get_called_class()), //对应 task.1 task.2
          'consumer_tag'      => 'mqTopic',
          'prefetch_size'     => 0,
          'prefetch_count'    => 30,
          'is_global'         => false,
      ]));
      sync_publish($b, json_encode($data));

```

请问我该如何实现?如果有demo最好!

**在次感谢作者无私奉献!**

**Comment by chaz6chez** [comment]
不好意思最近一直很忙没有看github；
关于这个问题，就是路由模式，1.X目前来说只能通过自行实现Builder来实现这个方案，也就是参照FastBuilder，自行实现一个Builder，在构造函数里进行注册队列，绑定队列等操作，比较麻烦；
还有一个方法，就是试一试2.X，不过目前2.X还是beta版，还没有时间去做CI相关内容，这段时间忙完会抽空去完善；
