### ISSUE TITLE
2.x rc版本同步发布队列任务返回异常

### ISSUE THREAD

**Issue by eriodesign** [workbunny/webman-rabbitmq#18]
2.0beta-rc2版本
sync_publish方法执行后提示错误：
Error: Call to a member function then() on bool in ～/x/vendor/workbunny/webman-rabbitmq/src/Connection.php:204

同步方法应该返回的是布尔值不是PromiseInterface，所以不可以继续链式执行->then等promise相关操作了。

如果是用法不对请有空指正，感谢

**Comment by chaz6chez** [comment]
好的，我修复一下

**Comment by chaz6chez** [comment]
已发布beta.3，可以尝试一下
