### ISSUE TITLE
这个包支持阿里云rabbitmq服务么?

### ISSUE THREAD

**Issue by ringer123** [workbunny/webman-rabbitmq#19]

**Comment by chaz6chez** [comment]
支持

**Comment by ringer123** [comment]
好的，我本地安装的rabbitmq，我有试可以生产、消费，
阿里云消息服务，我看官方给的demo用的是这个包 php-amqplib/php-amqplib
我按阿里云demo替换掉 user 和 password 用这个包，也没连上，我再试试看吧.
![image](https://github.com/workbunny/webman-rabbitmq/assets/28671887/2376e00a-59e4-4975-a5b2-0fbbe38c00d7)

**Comment by chaz6chez** [comment]
组件包基于bunny组件包，和php-amqplib/php-amqplib具备相同的功能；
阿里云队列rabbitmq版与开源版rabbitmq没有太多使用上的差别，注意为云账号实例授权，然后使用用户名密码即可连接；

**Comment by ringer123** [comment]
好的 可以直接用，非常感谢！
