### ISSUE TITLE
只发送消息，不消费

### ISSUE THREAD

**Issue by basar911** [workbunny/webman-rabbitmq#23]
我们项目的消费者在另一个系统已经建好，现在我只想发送消息不消费，应该怎么操作呢？

**Comment by chaz6chez** [comment]
> 我们项目的消费者在另一个系统已经建好，现在我只想发送消息不消费，应该怎么操作呢？

以下两种方案：
- 使用command命令将指定builder close即可
- 在config/plugin/workbunny/webman-rabbitmq/process.php中注释掉对应builder的消费者进程
