### ISSUE TITLE
Event-loop:Workerman\Events\Revolt不可用

### ISSUE THREAD

**Issue by corin11** [workbunny/webman-rabbitmq#24]
报错如下：
Error: Call to undefined method Workerman\Events\Revolt::add() in D:\EServer-3.5.3-win\core\www\ld-game-webman-api\vendor\workerman\rabbitmq\src\Client.php:158
Stack trace:
#0 D:\EServer-3.5.3-win\core\www\ld-game-webman-api\vendor\workbunny\webman-rabbitmq\src\Connection.php(93): Workerman\RabbitMQ\Client->connect()
#1 D:\EServer-3.5.3-win\core\www\ld-game-webman-api\vendor\workbunny\webman-rabbitmq\src\Builders\QueueBuilder.php(64): Workbunny\WebmanRabbitMQ\Connection->consume(Object(Workbunny\WebmanRabbitMQ\BuilderConfig))
#2 D:\EServer-3.5.3-win\core\www\ld-game-webman-api\support\helpers.php(432): Workbunny\WebmanRabbitMQ\Builders\QueueBuilder->onWorkerStart(Object(Workerman\Worker))
#3 D:\EServer-3.5.3-win\core\www\ld-game-webman-api\support\helpers.php(470): worker_bind(Object(Workerman\Worker), Object(process\workbunny\rabbitmq\RestyBuilder))
#4 D:\EServer-3.5.3-win\core\www\ld-game-webman-api\vendor\workerman\workerman\src\Worker.php(2443): {closure}(Object(Workerman\Worker))
#5 D:\EServer-3.5.3-win\core\www\ld-game-webman-api\vendor\workerman\workerman\src\Worker.php(1451): Workerman\Worker->run()
#6 D:\EServer-3.5.3-win\core\www\ld-game-webman-api\vendor\workerman\workerman\src\Worker.php(1370): Workerman\Worker::forkWorkersForWindows()
#7 D:\EServer-3.5.3-win\core\www\ld-game-webman-api\vendor\workerman\workerman\src\Worker.php(572): Workerman\Worker::forkWorkers()
#8 D:\EServer-3.5.3-win\core\www\ld-game-webman-api\runtime\windows\start_RestyBuilder.php(23): Workerman\Worker::runAll()
#9 {main}

**Comment by chaz6chez** [comment]
Workerman\Events\Revolt是workerman 5.x的特性，目前5.x还处于beta阶段；以下有两个方案可以采用：
1. 回退至workerman 4.x
2. 等待webman-rabbitmq兼容5.x
