### ISSUE TITLE
Error: Call to a member function publish() on int in

### ISSUE THREAD

**Issue by df131** [workbunny/webman-rabbitmq#25]
`        for ($i=1;$i<=50000;$i++){
            sync_publish(TestBuilder::instance(),$msg,'',[],true);
        }`
调用时,发现channel一直涨,如何在发布时释放掉channel

**Comment by chaz6chez** [comment]
rabbitmq client的channel本身会复用，只有在闲置channel不够的情况下新增，循环测试中，由于循环迭代速度较快，消息发布的过程中channel都不存在闲置的情况，这时channel就会新增；

使用fo循环进行消息发送时，请酌情调高rabbitmq server的channel配置上限，并在webma-rabbitmq的配置中开启连接复用

**Comment by chaz6chez** [comment]
升级至2.1.5，配置中开启reuse_channel（reuse_channel=true），详情查看readme
