### ISSUE TITLE
安装完启动服务报错

### ISSUE THREAD

**Issue by geminioop** [workbunny/webman-rabbitmq#28]
环境 ：macos  M1 
PHP： php8.3
框架 ：webman  v1.5.19
 workbunny/webman-rabbitmq 2.1.4

大概描述，配置文件命令行生成，消费者也是默认生成testBulider 

启动webman 服务后报错如下 
TypeError: Workbunny\WebmanRabbitMQ\Connection::Workbunny\WebmanRabbitMQ\{closure}(): Argument #1 ($channel) must be of type Bunny\Channel, null given, called in /Users/songjianqiang/www/webman/vendor/react/promise/src/FulfilledPromise.php on line 28 and defined in /Users/songjianqiang/www/webman/vendor/workbunny/webman-rabbitmq/src/Connection.php:257

大概意思是channel 通道参数没有 null ？  没有看到配置文件哪里有定义 ，或者消费者能定义该属性？

**Comment by chaz6chez** [comment]
是否使用workerman5.x？
能否提供复现的最小样例
