### ISSUE TITLE
数据量比较大的时候会出现异常

### ISSUE THREAD

**Issue by orangeFanX** [workbunny/webman-rabbitmq#29]
业务当中调用rabbitmq比较多 会出现
`{"error":"Could not write data to socket.","line":325,"file":"/data/wwwroot/vendor/bunny/bunny/src/Bunny/AbstractClient.php"} `
打印日志出现以下错误
`{"options":{"enable":true,"host":"aliyuncs.com","vhost":"y","port":"5672","password":"","mechanisms":"AMQPLAIN","mechanism":"PLAIN","timeout":10,"restart_interval":0,"heartbeat":25,"heartbeat_callback":{"Closure":[]},"error_callback":{"Closure":[]},"reuse_connection":false,"async":false,"user":"user"},"queue":{"0":{"Bunny\\Protocol\\MethodChannelCloseOkFrame":{"type":1,"channel":1,"payloadSize":4,"payload":null,"classId":20,"methodId":41}},"1":{"Bunny\\Protocol\\MethodChannelCloseOkFrame":{"type":1,"channel":2,"payloadSize":4,"payload":null,"classId":20,"methodId":41}}` ，业务场景是跨服当中推送数据，利用vhost做数据隔离，不同vhost消费不同服务器的数据

<img width="329" alt="image" src="https://github.com/user-attachments/assets/4a8965cf-2e71-4aa8-8dbb-d98fd27ed0a9">

**Comment by chaz6chez** [comment]
同步写入的时候是依赖fwrite的，当返回Could not write data to socket.时代表fwrite发生了错误，返回了false；
![image](https://github.com/user-attachments/assets/af03934e-f05b-45d3-bd00-2bf5964244fe)

向一个网络地址写入时返回false，通常是因为写buffer被占满了，具体情况可以查看fwrite结合系统和实际情况分析：
[php-function fwrite](https://www.php.net/manual/zh/function.fwrite.php)

**Comment by orangeFanX** [comment]
目前定位到 可能是关闭链接 没有用上链接池 导致rabbitMQ连接数超出上限了 看看作者大大下一个版本是否出一个配置多vhost链接版本

**Comment by chaz6chez** [comment]
> 目前定位到 可能是关闭链接 没有用上链接池 导致rabbitMQ连接数超出上限了 看看作者大大下一个版本是否出一个配置多vhost链接版本

可以，那就计划在下版本中增加配置多个连接，类似于config/database一样，builder中可指定连接

**Comment by chaz6chez** [comment]
2.2.0版本增加连接可选模式，详细请阅读最新的readme
