### ISSUE TITLE
连接数和channel都很高 观测发现自动释放很满 但是会一直开新链接

### ISSUE THREAD

**Issue by orangeFanX** [workbunny/webman-rabbitmq#30]
<img width="806" alt="image" src="https://github.com/user-attachments/assets/a3d3e925-2c71-4cfd-bd89-5b6145b6a94c">
图上每次下降都是在执行reload后

**Comment by chaz6chez** [comment]
请描述一下使用场景，环境、插件版本，最好可以提供最小复现样例

**Comment by orangeFanX** [comment]
后续观测发现是在function.php中写了发送消息的方法，复用链接和通道并没有生效，可能是我使用的方法不对，然后我在调用的时候，使用close: true关闭了链接和通道，目前没有发现这个问题

**Comment by chaz6chez** [comment]
> 后续观测发现是在function.php中写了发送消息的方法，复用链接和通道并没有生效，可能是我使用的方法不对，然后我在调用的时候，使用close: true关闭了链接和通道，目前没有发现这个问题

好的，有问题随时issue
