### ISSUE TITLE
How to use Publish/Subscribe provided by RabbitMQ?

### ISSUE THREAD

**Issue by 935924279** [workbunny/webman-rabbitmq#9]
How to use Publish/Subscribe provided by RabbitMQ?

**Comment by chaz6chez** [comment]
not yet supported, need to wait for next ver.
maybe a week, or 2-3 days

**Comment by 935924279** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 935924279** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
